import { Geist, Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";
import { Toaster } from "react-hot-toast";
import Footer from "@/component/Footer";

const notoSerifFont = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${notoSerifFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Marquee></Marquee>
        <main className="bg-[#f1f2f6]">
          <div className="container mx-auto">
            {children}
          </div>
     
        </main>
        <Footer></Footer>

         <Toaster/>          
        
      </body>
    </html>
  );
}
